# This file was generated by GoReleaser. DO NOT EDIT.
cask "agent" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "9faac997f7d4a45bdab9461a7b82b28b38f30c0dde31275a9adb54075cb66a43"
      url "https://github.com/upstacked/agent-releases/releases/download/v#{version}/upstacked-agent_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "eb56f117f4adb7711d896c33049604d8e6714f991bc4a671f108419b97b60ca6"
      url "https://github.com/upstacked/agent-releases/releases/download/v#{version}/upstacked-agent_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "160fb0aea7eef2913169af201c0ab6f9dc59050e64b882bcddcf31923b0aa253"
      url "https://github.com/upstacked/agent-releases/releases/download/v#{version}/upstacked-agent_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a982a56ccd4b7d593b5ab2db41049f99ca88d956713586942abd6ccf55530003"
      url "https://github.com/upstacked/agent-releases/releases/download/v#{version}/upstacked-agent_#{version}_linux_arm64.tar.gz"
    end
  end

  name "agent"
  desc "Send this machine's logs, and syslog and flows from network devices, to Upstacked"
  homepage "https://sokkel.dev/upstacked/agent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "upstacked-agent"
  bash_completion "completions/upstacked-agent.bash"
  fish_completion "completions/upstacked-agent.fish"
  zsh_completion "completions/_upstacked-agent"

  postflight do
    # Downloaded binaries are quarantined by Gatekeeper, which makes the
    # first run fail with an unhelpful dialog.
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/upstacked-agent"]
    end
    # The service runs the binary Homebrew links, so an upgrade has just
    # replaced it. Restart the service onto the new one.
    if File.exist?("/Library/LaunchDaemons/dev.sokkel.upstacked-agent.plist")
      system_command "/bin/launchctl",
                     args: ["kickstart", "-k", "system/dev.sokkel.upstacked-agent"],
                     sudo: true
    end
  end

  zap launchctl: [
      "dev.sokkel.upstacked-agent",
    ],
    delete: [
      "/Library/LaunchDaemons/dev.sokkel.upstacked-agent.plist",
    ],
    trash: [
      "/usr/local/etc/upstacked-agent",
      "/usr/local/var/upstacked-agent",
      "/usr/local/var/log/upstacked-agent.log",
    ]

  caveats <<~EOS
    Connect the agent to Upstacked and start it as a service:
      sudo upstacked-agent setup
    Then check on it with:
      upstacked-agent doctor

    Before uninstalling, remove the service:
      sudo upstacked-agent service uninstall
  EOS
end
