# This file was generated by GoReleaser. DO NOT EDIT.
cask "agent" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "b0194e4c4094cddd6caa968727e6f287dfad03cc7f27ffe73afc2665d555700d"
      url "https://github.com//upstacked/agent-releases/releases/download/v#{version}/upstacked-agent_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f589178bfb7035ee9f967a0c09a3e363a95709e75b98e8b88c01a06655454523"
      url "https://github.com//upstacked/agent-releases/releases/download/v#{version}/upstacked-agent_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2f7b3f229015d42b3590a341ad5424e11de8834cbb908b08e10db00d33929544"
      url "https://github.com//upstacked/agent-releases/releases/download/v#{version}/upstacked-agent_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3d2c6609644c8ad95b0b7b799d269cab66bd044cc2ecca410d18286bdd99f2eb"
      url "https://github.com//upstacked/agent-releases/releases/download/v#{version}/upstacked-agent_#{version}_linux_amd64.tar.gz"
    end
  end

  name "agent"
  desc "Send this machine's logs, and syslog and flows from network devices, to Upstacked"
  homepage "https://sokkel.dev/upstacked/agent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "upstacked-agent"
  bash_completion "completions/upstacked-agent.bash"
  fish_completion "completions/upstacked-agent.fish"
  zsh_completion "completions/_upstacked-agent"

  postflight do
    # Downloaded binaries are quarantined by Gatekeeper, which makes the
    # first run fail with an unhelpful dialog.
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/upstacked-agent"]
    end
    # The service runs the binary Homebrew links, so an upgrade has just
    # replaced it. Restart the service onto the new one.
    if File.exist?("/Library/LaunchDaemons/dev.sokkel.upstacked-agent.plist")
      system_command "/bin/launchctl",
                     args: ["kickstart", "-k", "system/dev.sokkel.upstacked-agent"],
                     sudo: true
    end
  end

  zap launchctl: [
      "dev.sokkel.upstacked-agent",
    ],
    delete: [
      "/Library/LaunchDaemons/dev.sokkel.upstacked-agent.plist",
    ],
    trash: [
      "/usr/local/etc/upstacked-agent",
      "/usr/local/var/upstacked-agent",
      "/usr/local/var/log/upstacked-agent.log",
    ]

  caveats <<~EOS
    Connect the agent to Upstacked and start it as a service:
      sudo upstacked-agent setup
    Then check on it with:
      upstacked-agent doctor

    Before uninstalling, remove the service:
      sudo upstacked-agent service uninstall
  EOS
end
