# This file was generated by GoReleaser. DO NOT EDIT.
cask "agent" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "482caf9a3bf980a6c5040be06391336bbc158837e82c0227136caec4e0da5d90"
      url "https://github.com//upstacked/agent-releases/releases/download/v#{version}/upstacked-agent_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6633778932663a197a8a64e7bbdec2be0d43b3df8bf748f2bc4d9692d32aacf8"
      url "https://github.com//upstacked/agent-releases/releases/download/v#{version}/upstacked-agent_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9bda28cb69c2c502f6ec7d3e78e5d4209279e930d6cbfd18cbce487ca1ae947c"
      url "https://github.com//upstacked/agent-releases/releases/download/v#{version}/upstacked-agent_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e34a7dbcd6ae319fad559bfbc289d67e8c87febd06de8083d7e08921205c6939"
      url "https://github.com//upstacked/agent-releases/releases/download/v#{version}/upstacked-agent_#{version}_linux_amd64.tar.gz"
    end
  end

  name "agent"
  desc "Send this machine's logs, and syslog and flows from network devices, to Upstacked"
  homepage "https://sokkel.dev/upstacked/agent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "upstacked-agent"
  bash_completion "completions/upstacked-agent.bash"
  fish_completion "completions/upstacked-agent.fish"
  zsh_completion "completions/_upstacked-agent"

  postflight do
    # Downloaded binaries are quarantined by Gatekeeper, which makes the
    # first run fail with an unhelpful dialog.
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/upstacked-agent"]
    end
    # The service runs the binary Homebrew links, so an upgrade has just
    # replaced it. Restart the service onto the new one.
    if File.exist?("/Library/LaunchDaemons/dev.sokkel.upstacked-agent.plist")
      system_command "/bin/launchctl",
                     args: ["kickstart", "-k", "system/dev.sokkel.upstacked-agent"],
                     sudo: true
    end
  end

  zap launchctl: [
      "dev.sokkel.upstacked-agent",
    ],
    delete: [
      "/Library/LaunchDaemons/dev.sokkel.upstacked-agent.plist",
    ],
    trash: [
      "/usr/local/etc/upstacked-agent",
      "/usr/local/var/upstacked-agent",
      "/usr/local/var/log/upstacked-agent.log",
    ]

  caveats <<~EOS
    Connect the agent to Upstacked and start it as a service:
      sudo upstacked-agent setup
    Then check on it with:
      upstacked-agent doctor

    Before uninstalling, remove the service:
      sudo upstacked-agent service uninstall
  EOS
end
