# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli" do
  version "0.0.24"

  on_macos do
    on_arm do
      sha256 "c80fc2650f7e3ab0324b05d17a2d5996407af97ad159aa04c69713d3b7e8fd40"
      url "https://github.com/upstacked/cli/releases/download/v#{version}/ups_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "657f7be126f2e8d2823c987db165aeb8127b53a50e42d1113739fd406fb116ab"
      url "https://github.com/upstacked/cli/releases/download/v#{version}/ups_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "794dfc49875e905753260730480cb85ceb2ef17527247b9075f31a2f15f77150"
      url "https://github.com/upstacked/cli/releases/download/v#{version}/ups_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "deff3ecf216f8188d968850b648d11a77acf65587ff96f5dc4cd0cb7ebe5119f"
      url "https://github.com/upstacked/cli/releases/download/v#{version}/ups_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cli"
  desc "Operate Upstacked infrastructure from the terminal"
  homepage "https://github.com/upstacked/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ups"
  bash_completion "completions/ups.bash"
  fish_completion "completions/ups.fish"
  zsh_completion "completions/_ups"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/ups"]
    end
  end

  # No zap stanza required
end
