# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli" do
  version "0.0.10"

  on_macos do
    on_arm do
      sha256 "ff4db96b6603aa5a572aa6fea7a5b1de5eadbf2342a6797a1211d2275f6592b7"
      url "https://github.com/upstacked/cli/releases/download/v#{version}/ups_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a9b696b6a73eb185fc379d56a2321da845df0fc64deb5196e9504d7d8507e96c"
      url "https://github.com/upstacked/cli/releases/download/v#{version}/ups_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "73e2d359bd260ecfecfc164bff6ca21f89df5295c2a2748834da0a7e3fb4f873"
      url "https://github.com/upstacked/cli/releases/download/v#{version}/ups_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b4d940fee0d11c920bdea306fbf2556bf3915fbacd297e73b1afc0ac12598b0d"
      url "https://github.com/upstacked/cli/releases/download/v#{version}/ups_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cli"
  desc "Operate Upstacked infrastructure from the terminal"
  homepage "https://github.com/upstacked/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ups"
  bash_completion "completions/ups.bash"
  fish_completion "completions/ups.fish"
  zsh_completion "completions/_ups"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/ups"]
    end
  end

  # No zap stanza required
end
