# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli" do
  version "0.0.20"

  on_macos do
    on_arm do
      sha256 "421ee28939e88455f5ae2763e6d5c2e2c31a63700155e8255537e2f6982239b9"
      url "https://github.com/upstacked/cli/releases/download/v#{version}/ups_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "dce381188409e8e692a46c17d19b75ceb9095b4b2898094cc5d594839611eda5"
      url "https://github.com/upstacked/cli/releases/download/v#{version}/ups_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0ec101d58e2c43d492431d6934998144d11b9d2e0168f6db27bd6d7352ef7f05"
      url "https://github.com/upstacked/cli/releases/download/v#{version}/ups_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8dba9726aea5a0642d4a67b44326d9eb08f37253d147b6790a647636af60415b"
      url "https://github.com/upstacked/cli/releases/download/v#{version}/ups_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cli"
  desc "Operate Upstacked infrastructure from the terminal"
  homepage "https://github.com/upstacked/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ups"
  bash_completion "completions/ups.bash"
  fish_completion "completions/ups.fish"
  zsh_completion "completions/_ups"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/ups"]
    end
  end

  # No zap stanza required
end
